name: Deploy to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Print current working directory
      run: pwd

    - name: List contents of the current directory
      run: ls -R

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Use SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: |
          ${{ secrets.ghostsshkey }}


    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-central-1

    - name: Set up SSH
      run: |
        echo "${{ secrets.ghostsshkey }}" > ./ssh/id_rsa
        chmod 600 ./ssh/id_rsa
